version: '3.8'

services:
  app:
    build:
      context: /var/www/report/web-ntbs
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - /var/www/report/web-ntbs:/var/www/report/web-ntbs
    networks:
      - laravel-network

  web:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /var/www/report/web-ntbs:/var/www/report/web-ntbs
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
